package gate

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/Gere2/neurofs/internal/abeval"
	"github.com/Gere2/neurofs/internal/config"
	"github.com/Gere2/neurofs/internal/embeddings"
	"github.com/Gere2/neurofs/internal/fsutil"
	"github.com/Gere2/neurofs/internal/indexer"
	"github.com/Gere2/neurofs/internal/storage"
)

const (
	// CrossShapeSchemaVersion identifies the immutable on-disk evidence
	// contract. A new contract must use a new version rather than changing
	// the interpretation of already-recorded runs.
	CrossShapeSchemaVersion       = 2
	legacyCrossShapeSchemaVersion = 1

	CrossShapeSignalKind = "mechanical_cross_shape"

	CrossShapeKindGoService          = "go_service"
	CrossShapeKindPythonLibrary      = "python_library"
	CrossShapeKindTypeScriptFrontend = "typescript_frontend"

	maxCrossShapeEvidenceBytes = int64(1 << 20)

	crossShapeMinTokenReduction = 0.25
	crossShapeMaxMissRate       = 1.0 / 3.0
	crossShapeMinFixtures       = 5
	crossShapeMinMeanRecall     = 0.8
	crossShapeFloatEpsilon      = 1e-12

	crossShapeEconomySearchLimit = 8
	crossShapeFixtureBudget      = 8000
	crossShapeMaxFutureSkew      = 5 * time.Minute
	crossShapeEmbeddingModel     = "mock-lcg"
)

var crossShapePinnedCommitPattern = regexp.MustCompile(`(?i)\b[0-9a-f]{40}\b`)

// BuildSourceTreeSHA256 is injected into release/build binaries with
// -ldflags. A G5 attestation refuses an empty or mismatched value so an old
// executable cannot claim measurements for a newer engine checkout merely
// because the caller points --g5-engine-root at it.
var BuildSourceTreeSHA256 string

// CrossShapeEvidence is one immutable mechanical G5 measurement. ActorKind
// records who ran the measurement; unlike G1, G5 is a mechanical signal, so
// either an agent or a human may produce valid evidence.
type CrossShapeEvidence struct {
	SchemaVersion    int                       `json:"schema_version"`
	MeasuredAt       string                    `json:"measured_at"`
	ActorKind        string                    `json:"actor_kind"`
	SignalKind       string                    `json:"signal_kind"`
	BinarySHA256     string                    `json:"binary_sha256"`
	WeightsSHA256    string                    `json:"weights_sha256"`
	SourceTreeSHA256 string                    `json:"source_tree_sha256"`
	RunConfig        *CrossShapeRunConfig      `json:"run_config,omitempty"`
	Shapes           []CrossShapeShapeEvidence `json:"shapes"`
	sourcePath       string
}

// CrossShapeRunConfig makes the mechanical run reproducible instead of
// leaving material CLI defaults implicit in prose.
type CrossShapeRunConfig struct {
	EmbeddingProvider  string `json:"embedding_provider"`
	EmbeddingModel     string `json:"embedding_model"`
	EconomySearchLimit int    `json:"economy_search_limit"`
	FixtureBudget      int    `json:"fixture_budget"`
	NoChunks           bool   `json:"no_chunks"`
	MockSemantic       bool   `json:"mock_semantic"`
}

// CrossShapeReportMetadata is generated by the measured executable when
// --g5-attest is enabled. It binds both raw reports to the actual binary,
// weights, fixture set, embedding space, and target checkout used by the run.
type CrossShapeReportMetadata struct {
	BinarySHA256           string `json:"binary_sha256"`
	EngineSourceTreeSHA256 string `json:"engine_source_tree_sha256"`
	TargetSourceTreeSHA256 string `json:"target_source_tree_sha256"`
	WeightsSHA256          string `json:"weights_sha256"`
	FixtureSetSHA256       string `json:"fixture_set_sha256"`
	EmbeddingProvider      string `json:"embedding_provider"`
	EmbeddingModel         string `json:"embedding_model"`
	MockSemantic           bool   `json:"mock_semantic"`
	RepoCommitSHA          string `json:"repo_commit_sha"`
	RepoRemoteURL          string `json:"repo_remote_url"`
	RepoDirty              bool   `json:"repo_dirty"`
}

// CrossShapeGateInvocation records the flags that materially affect G3.
type CrossShapeGateInvocation struct {
	FixtureBudget  int                                  `json:"fixture_budget"`
	NoChunks       bool                                 `json:"no_chunks"`
	MaxFixtures    int                                  `json:"max_fixtures"`
	SkipFixtures   bool                                 `json:"skip_fixtures"`
	FixtureBundles []CrossShapeFixtureBundleAttestation `json:"fixture_bundles"`
}

// CrossShapeFixtureBundleAttestation binds G2 to the exact fresh bundle
// produced for each G3 fixture in the same gate invocation. BundleHash is
// taskflow's stable canonical-content hash (GeneratedAt is deliberately not
// part of it), so no copied bundle directory or second pass is required.
type CrossShapeFixtureBundleAttestation struct {
	FixtureSource  string `json:"fixture_source"`
	QuestionSHA256 string `json:"question_sha256"`
	BundleHash     string `json:"bundle_hash"`
	TokensUsed     int    `json:"tokens_used"`
	TokensBudget   int    `json:"tokens_budget"`
}

// CrossShapeShapeEvidence contains the measurements for one repository
// shape. The three core sections are gate inputs; Bench is supplementary.
type CrossShapeShapeEvidence struct {
	Name             string                    `json:"name"`
	Kind             string                    `json:"kind"`
	RepoURL          string                    `json:"repo_url"`
	CommitSHA        string                    `json:"commit_sha"`
	FixtureSetSHA256 string                    `json:"fixture_set_sha256"`
	Economy          CrossShapeEconomyEvidence `json:"economy"`
	G2               CrossShapeG2Evidence      `json:"g2"`
	G3               CrossShapeG3Evidence      `json:"g3"`
	Bench            *CrossShapeBenchEvidence  `json:"bench,omitempty"`
}

type CrossShapeEconomyEvidence struct {
	Verdict            Verdict `json:"verdict"`
	MeanTokenReduction float64 `json:"mean_token_reduction"`
	OverallRecall      float64 `json:"overall_recall"`
	MissRate           float64 `json:"miss_rate"`
	ReportSHA256       string  `json:"report_sha256"`
}

type CrossShapeG2Evidence struct {
	Verdict      Verdict `json:"verdict"`
	Bundles      int     `json:"bundles"`
	Overshoots   int     `json:"overshoots"`
	ReportSHA256 string  `json:"report_sha256,omitempty"`
}

type CrossShapeG3Evidence struct {
	Verdict      Verdict `json:"verdict"`
	MeanRecall   float64 `json:"mean_recall"`
	Fixtures     int     `json:"fixtures"`
	Perfect      int     `json:"perfect"`
	ReportSHA256 string  `json:"report_sha256,omitempty"`
}

// CrossShapeCurrentIdentity is the part of a run identity that can be
// re-derived from a checkout. BinarySHA256 remains in evidence as an exact
// trace of the measured artifact, but is not compared here: release builds
// deliberately stamp a version into the executable, so byte identity changes
// across an otherwise source-identical commit. Source, weights, and fixture
// identity cover every input that affects the measured retrieval behavior.
type CrossShapeCurrentIdentity struct {
	SourceTreeSHA256  string
	WeightsSHA256     string
	TargetSourceTrees map[string]string
	FixtureSets       map[string]string
	FixtureCounts     map[string]int
	PinnedCommits     map[string]string
	Fixtures          map[string][]Fixture
}

// CrossShapeBenchEvidence is intentionally not part of the G5 verdict. It
// preserves the file-ranker health check next to the core measurements.
type CrossShapeBenchEvidence struct {
	Questions    int     `json:"questions"`
	Top3Percent  float64 `json:"top3_percent"`
	ReportSHA256 string  `json:"report_sha256"`
}

type loadedCrossShapeEvidence struct {
	path       string
	measuredAt time.Time
	evidence   CrossShapeEvidence
}

// LoadCrossShapeEvidence reads immutable *.json runs directly under dir and
// returns the most recently measured valid run. Missing or empty directories
// are a normal "no evidence" state. Evidence files are bounded to 1 MiB.
// A JSON-named symlink or non-regular entry is rejected: silently ignoring it
// could hide what an operator reasonably believes is gate evidence.
//
// Every candidate JSON file must be valid. Silently dropping malformed
// evidence could hide a failing run and incorrectly turn G5 green.
func LoadCrossShapeEvidence(dir string) (*CrossShapeEvidence, error) {
	info, err := os.Lstat(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("gate: inspect cross-shape evidence dir: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return nil, fmt.Errorf("gate: cross-shape evidence path must be a real directory: %s", dir)
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("gate: read cross-shape evidence dir: %w", err)
	}
	runs := make([]loadedCrossShapeEvidence, 0, len(entries))
	for _, entry := range entries {
		if !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return nil, fmt.Errorf("gate: cross-shape evidence %s must not be a symlink", entry.Name())
		}
		entryInfo, err := entry.Info()
		if err != nil {
			return nil, fmt.Errorf("gate: inspect cross-shape evidence %s: %w", entry.Name(), err)
		}
		if !entryInfo.Mode().IsRegular() {
			return nil, fmt.Errorf("gate: cross-shape evidence %s must be a regular file", entry.Name())
		}

		path := filepath.Join(dir, entry.Name())
		data, _, err := fsutil.ReadRegularFileBounded(path, maxCrossShapeEvidenceBytes)
		if err != nil {
			return nil, fmt.Errorf("gate: read cross-shape evidence %s: %w", path, err)
		}
		var evidence CrossShapeEvidence
		if err := decodeCrossShapeEvidence(data, &evidence); err != nil {
			return nil, fmt.Errorf("gate: parse cross-shape evidence %s: %w", path, err)
		}
		measuredAt, err := validateCrossShapeEvidence(&evidence)
		if err != nil {
			return nil, fmt.Errorf("gate: validate cross-shape evidence %s: %w", path, err)
		}
		evidence.sourcePath = path
		runs = append(runs, loadedCrossShapeEvidence{
			path:       path,
			measuredAt: measuredAt,
			evidence:   evidence,
		})
	}
	if len(runs) == 0 {
		return nil, nil
	}

	sort.Slice(runs, func(i, j int) bool {
		if runs[i].measuredAt.Equal(runs[j].measuredAt) {
			return runs[i].path < runs[j].path
		}
		return runs[i].measuredAt.Before(runs[j].measuredAt)
	})
	latest := runs[len(runs)-1].evidence
	return &latest, nil
}

func decodeCrossShapeEvidence(data []byte, evidence *CrossShapeEvidence) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(evidence); err != nil {
		return err
	}
	var trailing json.RawMessage
	if err := decoder.Decode(&trailing); err != io.EOF {
		if err == nil {
			return fmt.Errorf("multiple JSON values")
		}
		return fmt.Errorf("trailing data: %w", err)
	}
	return nil
}

// EvaluateG5 evaluates a validated cross-shape run. It deliberately does not
// use the optional bench result: bench is a regression diagnostic, while G5
// requires economy, G2, and G3 to pass on every required repository shape.
func EvaluateG5(evidence *CrossShapeEvidence) Criterion {
	criterion := Criterion{ID: "G5", Name: "Cross-shape sanity"}
	if evidence == nil {
		criterion.Verdict = Skip
		criterion.Detail = "no cross-shape evidence available"
		return criterion
	}

	if _, err := validateCrossShapeEvidence(evidence); err != nil {
		criterion.Verdict = Fail
		criterion.Detail = "invalid cross-shape evidence: " + err.Error()
		return criterion
	}

	criterion.Numbers = map[string]float64{
		"shapes":              float64(len(evidence.Shapes)),
		"required_shapes":     3,
		"min_token_reduction": crossShapeMinTokenReduction,
		"max_miss_rate":       crossShapeMaxMissRate,
		"min_g3_fixtures":     crossShapeMinFixtures,
		"min_g3_mean_recall":  crossShapeMinMeanRecall,
	}

	presentKinds := make(map[string]bool, len(evidence.Shapes))
	shapes := append([]CrossShapeShapeEvidence(nil), evidence.Shapes...)
	sort.Slice(shapes, func(i, j int) bool {
		if shapes[i].Kind == shapes[j].Kind {
			return shapes[i].Name < shapes[j].Name
		}
		return shapes[i].Kind < shapes[j].Kind
	})

	var failures []string
	for _, shape := range shapes {
		presentKinds[shape.Kind] = true
		prefix := fmt.Sprintf("%s (%s)", shape.Name, shape.Kind)
		if shape.Economy.Verdict != Pass {
			failures = append(failures, fmt.Sprintf("%s economy verdict is %s", prefix, shape.Economy.Verdict))
		}
		if shape.Economy.MeanTokenReduction+crossShapeFloatEpsilon < crossShapeMinTokenReduction {
			failures = append(failures, fmt.Sprintf(
				"%s economy token reduction %.1f%% is below 25%%",
				prefix, shape.Economy.MeanTokenReduction*100,
			))
		}
		if shape.Economy.MissRate >= crossShapeMaxMissRate-crossShapeFloatEpsilon {
			failures = append(failures, fmt.Sprintf(
				"%s economy miss rate %.1f%% must be below 33.3%%",
				prefix, shape.Economy.MissRate*100,
			))
		}
		if shape.G2.Verdict != Pass {
			failures = append(failures, fmt.Sprintf("%s G2 verdict is %s", prefix, shape.G2.Verdict))
		}
		if shape.G2.Bundles <= 0 {
			failures = append(failures, fmt.Sprintf("%s G2 has no bundles", prefix))
		}
		if shape.G2.Overshoots != 0 {
			failures = append(failures, fmt.Sprintf("%s G2 has %d overshoots", prefix, shape.G2.Overshoots))
		}
		if shape.G3.Verdict != Pass {
			failures = append(failures, fmt.Sprintf("%s G3 verdict is %s", prefix, shape.G3.Verdict))
		}
		if shape.G3.Fixtures < crossShapeMinFixtures {
			failures = append(failures, fmt.Sprintf(
				"%s G3 has %d fixtures, need at least %d",
				prefix, shape.G3.Fixtures, crossShapeMinFixtures,
			))
		}
		if shape.G3.MeanRecall+crossShapeFloatEpsilon < crossShapeMinMeanRecall {
			failures = append(failures, fmt.Sprintf(
				"%s G3 mean recall %.1f%% is below 80%%",
				prefix, shape.G3.MeanRecall*100,
			))
		}
	}

	var missing []string
	for _, kind := range requiredCrossShapeKinds() {
		if !presentKinds[kind] {
			missing = append(missing, kind)
		}
	}
	if len(missing) > 0 {
		failures = append(failures, "missing required shapes: "+strings.Join(missing, ", "))
	}

	if len(failures) > 0 {
		criterion.Verdict = Fail
		criterion.Detail = strings.Join(failures, "; ")
		return criterion
	}

	criterion.Verdict = Pass
	criterion.Detail = fmt.Sprintf(
		"%d repository shapes meet economy, G2, and G3 thresholds (%s)",
		len(shapes), strings.Join(requiredCrossShapeKinds(), ", "),
	)
	return criterion
}

// EvaluateG5ForRepo additionally rejects mechanically valid but stale
// evidence. A historical PASS must not stay green after the engine, tuned
// weights, or canonical fixture sets change.
func EvaluateG5ForRepo(evidence *CrossShapeEvidence, repoRoot string) Criterion {
	criterion := EvaluateG5(evidence)
	if criterion.Verdict != Pass {
		return criterion
	}
	if evidence.SchemaVersion != CrossShapeSchemaVersion {
		criterion.Verdict = Fail
		criterion.Detail = fmt.Sprintf(
			"cross-shape evidence schema %d is historical; record a schema %d run against the current checkout",
			evidence.SchemaVersion, CrossShapeSchemaVersion,
		)
		return criterion
	}
	current, err := CurrentCrossShapeIdentity(repoRoot)
	if err != nil {
		criterion.Verdict = Fail
		criterion.Detail = "cannot verify cross-shape evidence freshness: " + err.Error()
		return criterion
	}
	if err := verifyCrossShapeReports(evidence, current); err != nil {
		criterion.Verdict = Fail
		criterion.Detail = "cross-shape report integrity failed: " + err.Error()
		return criterion
	}
	return EvaluateG5WithIdentity(evidence, current)
}

// verifyCrossShapeReports binds the summary fields to retained raw command
// output. For evidence audit/g5/<run>.json, artifacts live under
// audit/g5/reports/<run>/<shape-kind>-{economy,gate,bench}.{json,txt}.
func verifyCrossShapeReports(evidence *CrossShapeEvidence, current CrossShapeCurrentIdentity) error {
	if strings.TrimSpace(evidence.sourcePath) == "" {
		return fmt.Errorf("evidence source path is unavailable")
	}
	runName := strings.TrimSuffix(filepath.Base(evidence.sourcePath), filepath.Ext(evidence.sourcePath))
	reportDir := filepath.Join(filepath.Dir(evidence.sourcePath), "reports", runName)
	for _, shape := range evidence.Shapes {
		fixtures, ok := current.Fixtures[shape.Kind]
		if !ok {
			return fmt.Errorf("%s canonical fixtures are unavailable", shape.Kind)
		}
		economyPath := filepath.Join(reportDir, shape.Kind+"-economy.json")
		economyData, economyHash, err := readCrossShapeReport(economyPath)
		if err != nil {
			return fmt.Errorf("%s economy report: %w", shape.Kind, err)
		}
		if economyHash != shape.Economy.ReportSHA256 {
			return fmt.Errorf("%s economy report hash mismatch", shape.Kind)
		}
		if err := verifyCrossShapeEconomyReport(economyData, evidence.RunConfig, shape, fixtures); err != nil {
			return fmt.Errorf("%s economy report metrics: %w", shape.Kind, err)
		}

		gatePath := filepath.Join(reportDir, shape.Kind+"-gate.json")
		gateData, gateHash, err := readCrossShapeReport(gatePath)
		if err != nil {
			return fmt.Errorf("%s gate report: %w", shape.Kind, err)
		}
		if gateHash != shape.G2.ReportSHA256 || gateHash != shape.G3.ReportSHA256 {
			return fmt.Errorf("%s gate report hash mismatch", shape.Kind)
		}
		if err := verifyCrossShapeGateReport(gateData, shape, fixtures); err != nil {
			return fmt.Errorf("%s gate report metrics: %w", shape.Kind, err)
		}
		if err := verifyCrossShapeReportAttestation(
			economyData,
			gateData,
			evidence,
			shape,
			fixtures,
			current.TargetSourceTrees,
		); err != nil {
			return fmt.Errorf("%s report attestation: %w", shape.Kind, err)
		}

		if shape.Bench != nil {
			benchPath := filepath.Join(reportDir, shape.Kind+"-bench.txt")
			benchData, benchHash, err := readCrossShapeReport(benchPath)
			if err != nil {
				return fmt.Errorf("%s bench report: %w", shape.Kind, err)
			}
			if benchHash != shape.Bench.ReportSHA256 {
				return fmt.Errorf("%s bench report hash mismatch", shape.Kind)
			}
			if err := verifyCrossShapeBenchReport(benchData, *shape.Bench); err != nil {
				return fmt.Errorf("%s bench report metrics: %w", shape.Kind, err)
			}
		}
	}
	return nil
}

type retainedEconomyReport struct {
	Repo        string                    `json:"repo"`
	SearchLimit int                       `json:"search_limit"`
	Summary     abeval.Summary            `json:"summary"`
	Tasks       []abeval.TaskResult       `json:"tasks"`
	G5Metadata  *CrossShapeReportMetadata `json:"g5_metadata,omitempty"`
}

func verifyCrossShapeEconomyReport(
	data []byte,
	runConfig *CrossShapeRunConfig,
	shape CrossShapeShapeEvidence,
	fixtures []Fixture,
) error {
	var report retainedEconomyReport
	if err := decodeSingleJSON(data, &report); err != nil {
		return err
	}
	if runConfig == nil || report.SearchLimit != runConfig.EconomySearchLimit {
		return fmt.Errorf(
			"search_limit = %d, evidence run_config = %v",
			report.SearchLimit, runConfig,
		)
	}
	if strings.TrimSpace(report.Repo) == "" {
		return fmt.Errorf("repo is empty")
	}
	if report.Summary.Tasks != len(report.Tasks) {
		return fmt.Errorf(
			"summary.tasks = %d, retained tasks = %d",
			report.Summary.Tasks, len(report.Tasks),
		)
	}
	if len(report.Tasks) != len(fixtures) {
		return fmt.Errorf("retained tasks = %d, canonical fixtures = %d", len(report.Tasks), len(fixtures))
	}
	for i := range report.Tasks {
		if err := verifyCrossShapeEconomyTask(report.Tasks[i], fixtures[i]); err != nil {
			return fmt.Errorf("tasks[%d]: %w", i, err)
		}
	}
	recomputed := abeval.Summarise(report.Tasks, abeval.Options{
		SearchLimit: report.SearchLimit,
		Threshold:   crossShapeMinTokenReduction,
	})
	if report.Summary != recomputed {
		return fmt.Errorf("summary does not match retained task rows")
	}
	if report.Summary.Tasks != shape.G3.Fixtures ||
		report.Summary.FactTasks != shape.G3.Fixtures {
		return fmt.Errorf(
			"task coverage = %d/%d fact, evidence fixtures = %d",
			report.Summary.Tasks, report.Summary.FactTasks, shape.G3.Fixtures,
		)
	}
	if Verdict(report.Summary.Verdict) != shape.Economy.Verdict {
		return fmt.Errorf(
			"verdict = %s, evidence = %s",
			report.Summary.Verdict, shape.Economy.Verdict,
		)
	}
	if !crossShapeFloatEqual(report.Summary.MeanTokenReduction, shape.Economy.MeanTokenReduction) {
		return fmt.Errorf(
			"mean_token_reduction = %.17g, evidence = %.17g",
			report.Summary.MeanTokenReduction, shape.Economy.MeanTokenReduction,
		)
	}
	if !crossShapeFloatEqual(report.Summary.OverallRecallNeurofs, shape.Economy.OverallRecall) {
		return fmt.Errorf(
			"overall_recall = %.17g, evidence = %.17g",
			report.Summary.OverallRecallNeurofs, shape.Economy.OverallRecall,
		)
	}
	if !crossShapeFloatEqual(report.Summary.MissRate, shape.Economy.MissRate) {
		return fmt.Errorf(
			"miss_rate = %.17g, evidence = %.17g",
			report.Summary.MissRate, shape.Economy.MissRate,
		)
	}
	return nil
}

func verifyCrossShapeReportAttestation(
	economyData []byte,
	gateData []byte,
	evidence *CrossShapeEvidence,
	shape CrossShapeShapeEvidence,
	fixtures []Fixture,
	currentTargetSourceTrees map[string]string,
) error {
	var economyEnvelope struct {
		Metadata *CrossShapeReportMetadata `json:"g5_metadata"`
	}
	if err := decodeSingleJSON(economyData, &economyEnvelope); err != nil {
		return fmt.Errorf("decode economy metadata: %w", err)
	}
	var gateEnvelope struct {
		Metadata   *CrossShapeReportMetadata `json:"g5_metadata"`
		Invocation *CrossShapeGateInvocation `json:"g5_gate_invocation"`
	}
	if err := decodeSingleJSON(gateData, &gateEnvelope); err != nil {
		return fmt.Errorf("decode gate metadata: %w", err)
	}
	if economyEnvelope.Metadata == nil || gateEnvelope.Metadata == nil {
		return fmt.Errorf("both reports must contain --g5-attest metadata")
	}
	if *economyEnvelope.Metadata != *gateEnvelope.Metadata {
		return fmt.Errorf("economy and gate runtime metadata differ")
	}
	metadata := economyEnvelope.Metadata
	if metadata.BinarySHA256 != evidence.BinarySHA256 {
		return fmt.Errorf("binary hash does not match evidence")
	}
	if metadata.EngineSourceTreeSHA256 != evidence.SourceTreeSHA256 {
		return fmt.Errorf("engine source-tree hash does not match evidence")
	}
	if err := validateSHA256(
		"target source-tree hash",
		metadata.TargetSourceTreeSHA256,
	); err != nil {
		return err
	}
	if shape.Kind == CrossShapeKindGoService {
		currentTargetHash, ok := currentTargetSourceTrees[shape.Kind]
		if !ok {
			return fmt.Errorf("current Go target source-tree hash is unavailable")
		}
		if metadata.TargetSourceTreeSHA256 != currentTargetHash {
			return fmt.Errorf(
				"target source-tree hash does not match the current Go indexed tree",
			)
		}
	}
	if metadata.WeightsSHA256 != evidence.WeightsSHA256 {
		return fmt.Errorf("weights hash does not match evidence")
	}
	if metadata.FixtureSetSHA256 != shape.FixtureSetSHA256 {
		return fmt.Errorf("fixture-set hash does not match evidence")
	}
	if metadata.EmbeddingProvider != evidence.RunConfig.EmbeddingProvider ||
		metadata.EmbeddingModel != evidence.RunConfig.EmbeddingModel ||
		metadata.MockSemantic != evidence.RunConfig.MockSemantic {
		return fmt.Errorf("embedding runtime does not match run_config")
	}
	if metadata.RepoCommitSHA != shape.CommitSHA {
		return fmt.Errorf("checkout commit does not match evidence")
	}
	if normalizeCrossShapeRepoURL(metadata.RepoRemoteURL) !=
		normalizeCrossShapeRepoURL(shape.RepoURL) {
		return fmt.Errorf("checkout origin does not match evidence repo_url")
	}
	if shape.Kind != CrossShapeKindGoService && metadata.RepoDirty {
		return fmt.Errorf("external canonical checkout is dirty")
	}
	if gateEnvelope.Invocation == nil {
		return fmt.Errorf("gate report must contain --g5-attest invocation")
	}
	invocation := gateEnvelope.Invocation
	if invocation.FixtureBudget != evidence.RunConfig.FixtureBudget ||
		invocation.NoChunks != evidence.RunConfig.NoChunks ||
		invocation.MaxFixtures != 0 ||
		invocation.SkipFixtures {
		return fmt.Errorf("gate invocation is not the canonical full-fixture run")
	}
	if err := verifyCrossShapeFixtureBundles(
		invocation.FixtureBundles,
		fixtures,
		shape.G2,
		evidence.RunConfig.FixtureBudget,
	); err != nil {
		return err
	}
	return nil
}

func verifyCrossShapeFixtureBundles(
	bundles []CrossShapeFixtureBundleAttestation,
	fixtures []Fixture,
	g2 CrossShapeG2Evidence,
	fixtureBudget int,
) error {
	if len(bundles) != len(fixtures) {
		return fmt.Errorf(
			"G2 fixture bundle count = %d, canonical fixtures = %d",
			len(bundles), len(fixtures),
		)
	}
	overshoots := 0
	for i, fixture := range fixtures {
		bundle := bundles[i]
		if bundle.FixtureSource != filepath.Base(fixture.SourcePath) {
			return fmt.Errorf(
				"G2 fixture_bundles[%d].fixture_source = %q, want %q",
				i, bundle.FixtureSource, filepath.Base(fixture.SourcePath),
			)
		}
		questionDigest := sha256.Sum256([]byte(fixture.Question))
		if bundle.QuestionSHA256 != hex.EncodeToString(questionDigest[:]) {
			return fmt.Errorf("G2 fixture_bundles[%d] question hash mismatch", i)
		}
		if err := validateSHA256(
			fmt.Sprintf("G2 fixture_bundles[%d].bundle_hash", i),
			bundle.BundleHash,
		); err != nil {
			return err
		}
		if bundle.TokensBudget != fixtureBudget {
			return fmt.Errorf(
				"G2 fixture_bundles[%d].tokens_budget = %d, want %d",
				i, bundle.TokensBudget, fixtureBudget,
			)
		}
		if bundle.TokensUsed < 0 {
			return fmt.Errorf("G2 fixture_bundles[%d].tokens_used must be non-negative", i)
		}
		if bundle.TokensUsed > bundle.TokensBudget {
			overshoots++
		}
	}
	if g2.Bundles != len(bundles) || g2.Overshoots != overshoots {
		return fmt.Errorf(
			"G2 evidence %d bundles/%d overshoots does not match fixture bundles %d/%d",
			g2.Bundles, g2.Overshoots, len(bundles), overshoots,
		)
	}
	return nil
}

func normalizeCrossShapeRepoURL(value string) string {
	value = strings.TrimSpace(strings.ToLower(value))
	value = strings.TrimSuffix(value, "/")
	value = strings.TrimSuffix(value, ".git")
	return value
}

func verifyCrossShapeGateReport(
	data []byte,
	shape CrossShapeShapeEvidence,
	fixtures []Fixture,
) error {
	var report Report
	if err := decodeSingleJSON(data, &report); err != nil {
		return err
	}
	g2, err := uniqueCrossShapeCriterion(report.Criteria, "G2")
	if err != nil {
		return err
	}
	g3, err := uniqueCrossShapeCriterion(report.Criteria, "G3")
	if err != nil {
		return err
	}
	if g2.Verdict != shape.G2.Verdict {
		return fmt.Errorf("G2 verdict = %s, evidence = %s", g2.Verdict, shape.G2.Verdict)
	}
	if err := verifyCrossShapeIntegerMetric(g2, "bundles", shape.G2.Bundles); err != nil {
		return err
	}
	if err := verifyCrossShapeIntegerMetric(g2, "overshoots", shape.G2.Overshoots); err != nil {
		return err
	}
	if g3.Verdict != shape.G3.Verdict {
		return fmt.Errorf("G3 verdict = %s, evidence = %s", g3.Verdict, shape.G3.Verdict)
	}
	if err := verifyCrossShapeIntegerMetric(g3, "fixtures", shape.G3.Fixtures); err != nil {
		return err
	}
	if err := verifyCrossShapeIntegerMetric(g3, "perfect", shape.G3.Perfect); err != nil {
		return err
	}
	meanRecall, ok := g3.Numbers["mean_recall"]
	if !ok || !crossShapeFloatEqual(meanRecall, shape.G3.MeanRecall) {
		return fmt.Errorf(
			"G3 mean_recall = %.17g (present=%t), evidence = %.17g",
			meanRecall, ok, shape.G3.MeanRecall,
		)
	}
	if len(report.G3Details) != shape.G3.Fixtures {
		return fmt.Errorf(
			"G3 detail count = %d, evidence fixtures = %d",
			len(report.G3Details), shape.G3.Fixtures,
		)
	}
	if len(report.G3Details) != len(fixtures) {
		return fmt.Errorf(
			"G3 detail count = %d, canonical fixtures = %d",
			len(report.G3Details), len(fixtures),
		)
	}
	for i := range report.G3Details {
		if err := verifyCrossShapeFactResult(report.G3Details[i], fixtures[i]); err != nil {
			return fmt.Errorf("G3 details[%d]: %w", i, err)
		}
	}
	recomputedG3 := EvaluateG3(report.G3Details, DefaultG3Thresholds())
	if recomputedG3.Verdict != g3.Verdict ||
		!crossShapeFloatEqual(recomputedG3.Numbers["fixtures"], g3.Numbers["fixtures"]) ||
		!crossShapeFloatEqual(recomputedG3.Numbers["perfect"], g3.Numbers["perfect"]) ||
		!crossShapeFloatEqual(recomputedG3.Numbers["mean_recall"], g3.Numbers["mean_recall"]) {
		return fmt.Errorf("G3 criterion does not match retained fixture rows")
	}
	return nil
}

func verifyCrossShapeEconomyTask(task abeval.TaskResult, fixture Fixture) error {
	if task.Question != fixture.Question {
		return fmt.Errorf("question does not match canonical fixture")
	}
	if task.Source != filepath.Base(fixture.SourcePath) {
		return fmt.Errorf("source %q does not match %q", task.Source, filepath.Base(fixture.SourcePath))
	}
	facts := nonBlankFixtureFacts(fixture.ExpectsFacts)
	if !task.HasFacts || len(facts) == 0 {
		return fmt.Errorf("task must carry canonical facts")
	}
	if err := verifyCrossShapeArm("neurofs", task.Neurofs, facts); err != nil {
		return err
	}
	if err := verifyCrossShapeArm("native_iso", task.NativeIso, facts); err != nil {
		return err
	}
	if task.Scored {
		if task.Neurofs.Tokens <= 0 || task.NativeIso.Tokens <= 0 {
			return fmt.Errorf("scored task tokens must be positive")
		}
		if task.NativeIso.Recall+crossShapeFloatEpsilon < task.Neurofs.Recall {
			return fmt.Errorf("native recall is below neurofs recall")
		}
		wantReduction := 1 - float64(task.Neurofs.Tokens)/float64(task.NativeIso.Tokens)
		if !crossShapeFloatEqual(task.TokenReduction, wantReduction) {
			return fmt.Errorf("token_reduction does not match arm tokens")
		}
	} else {
		if task.Neurofs.Recall != 0 || !strings.Contains(task.Note, "search miss") {
			return fmt.Errorf("unscored fact task must be a zero-recall search miss")
		}
		if task.TokenReduction != 0 {
			return fmt.Errorf("unscored task must have zero token_reduction")
		}
	}
	return nil
}

func verifyCrossShapeArm(name string, arm abeval.Arm, facts []string) error {
	if arm.Tokens < 0 {
		return fmt.Errorf("%s tokens must be non-negative", name)
	}
	if err := validateRatio(name+".recall", arm.Recall); err != nil {
		return err
	}
	seen := make(map[string]bool, len(arm.FactsHit))
	for _, hit := range arm.FactsHit {
		if seen[hit] || !containsCrossShapeString(facts, hit) {
			return fmt.Errorf("%s facts_hit is not a unique canonical subset", name)
		}
		seen[hit] = true
	}
	wantRecall := float64(len(arm.FactsHit)) / float64(len(facts))
	if !crossShapeFloatEqual(arm.Recall, wantRecall) {
		return fmt.Errorf("%s recall does not match facts_hit", name)
	}
	return nil
}

func verifyCrossShapeFactResult(result FactResult, fixture Fixture) error {
	if result.Fixture.Question != fixture.Question ||
		result.Fixture.Source != fixture.Source ||
		result.Fixture.Supersedes != fixture.Supersedes ||
		filepath.Base(result.Fixture.SourcePath) != filepath.Base(fixture.SourcePath) ||
		!equalCrossShapeStrings(result.Fixture.ExpectsFacts, fixture.ExpectsFacts) {
		return fmt.Errorf("fixture does not match canonical input")
	}
	if result.Error != "" {
		if result.Recall != 0 {
			return fmt.Errorf("errored fixture must have zero recall")
		}
		return nil
	}
	facts := nonBlankFixtureFacts(fixture.ExpectsFacts)
	seen := make(map[string]bool, len(result.Hits))
	for _, hit := range result.Hits {
		if seen[hit] || !containsCrossShapeString(facts, hit) {
			return fmt.Errorf("hits is not a unique canonical subset")
		}
		seen[hit] = true
	}
	wantMisses := make([]string, 0, len(facts)-len(result.Hits))
	for _, fact := range facts {
		if !seen[fact] {
			wantMisses = append(wantMisses, fact)
		}
	}
	if !equalCrossShapeStrings(result.Misses, wantMisses) {
		return fmt.Errorf("misses does not complement hits")
	}
	wantRecall := float64(len(result.Hits)) / float64(len(facts))
	if !crossShapeFloatEqual(result.Recall, wantRecall) {
		return fmt.Errorf("recall does not match hits")
	}
	for _, stale := range result.StaleFacts {
		if !containsCrossShapeString(result.Misses, stale) {
			return fmt.Errorf("stale_facts is not a subset of misses")
		}
	}
	return nil
}

func containsCrossShapeString(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}

func equalCrossShapeStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func verifyCrossShapeBenchReport(data []byte, evidence CrossShapeBenchEvidence) error {
	questionsPattern := regexp.MustCompile(`(?m)^\s*questions\s*:\s*([0-9]+)\s*$`)
	top3Pattern := regexp.MustCompile(`(?m)^\s*top-3\s*:\s*([0-9]+(?:\.[0-9]+)?)%\s*$`)
	questionsMatch := questionsPattern.FindSubmatch(data)
	top3Match := top3Pattern.FindSubmatch(data)
	if len(questionsMatch) != 2 || len(top3Match) != 2 {
		return fmt.Errorf("cannot find questions/top-3 summary")
	}
	questions, err := strconv.Atoi(string(questionsMatch[1]))
	if err != nil {
		return fmt.Errorf("parse questions: %w", err)
	}
	top3, err := strconv.ParseFloat(string(top3Match[1]), 64)
	if err != nil {
		return fmt.Errorf("parse top-3: %w", err)
	}
	if questions != evidence.Questions {
		return fmt.Errorf("questions = %d, evidence = %d", questions, evidence.Questions)
	}
	// The text renderer intentionally rounds percentages to one decimal.
	if math.Abs(top3-evidence.Top3Percent) > 0.05+crossShapeFloatEpsilon {
		return fmt.Errorf("top-3 = %.1f, evidence = %.17g", top3, evidence.Top3Percent)
	}
	return nil
}

func readCrossShapeReport(path string) ([]byte, string, error) {
	data, _, err := fsutil.ReadRegularFileBounded(path, maxCrossShapeEvidenceBytes)
	if err != nil {
		return nil, "", err
	}
	sum := sha256.Sum256(data)
	return data, hex.EncodeToString(sum[:]), nil
}

func decodeSingleJSON(data []byte, target any) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	if err := decoder.Decode(target); err != nil {
		return err
	}
	var trailing json.RawMessage
	if err := decoder.Decode(&trailing); err != io.EOF {
		if err == nil {
			return fmt.Errorf("multiple JSON values")
		}
		return fmt.Errorf("trailing data: %w", err)
	}
	return nil
}

func uniqueCrossShapeCriterion(criteria []Criterion, id string) (Criterion, error) {
	var found *Criterion
	for i := range criteria {
		if criteria[i].ID != id {
			continue
		}
		if found != nil {
			return Criterion{}, fmt.Errorf("duplicate %s criterion", id)
		}
		copy := criteria[i]
		found = &copy
	}
	if found == nil {
		return Criterion{}, fmt.Errorf("missing %s criterion", id)
	}
	return *found, nil
}

func verifyCrossShapeIntegerMetric(criterion Criterion, name string, want int) error {
	value, ok := criterion.Numbers[name]
	if !ok || !isFinite(value) || math.Trunc(value) != value || int(value) != want {
		return fmt.Errorf(
			"%s %s = %.17g (present=%t), evidence = %d",
			criterion.ID, name, value, ok, want,
		)
	}
	return nil
}

func crossShapeFloatEqual(a, b float64) bool {
	return math.Abs(a-b) <= crossShapeFloatEpsilon
}

// EvaluateG5WithIdentity is the pure freshness comparison used by
// EvaluateG5ForRepo and unit tests.
func EvaluateG5WithIdentity(evidence *CrossShapeEvidence, current CrossShapeCurrentIdentity) Criterion {
	criterion := EvaluateG5(evidence)
	if criterion.Verdict != Pass {
		return criterion
	}
	if evidence.SchemaVersion != CrossShapeSchemaVersion {
		criterion.Verdict = Fail
		criterion.Detail = fmt.Sprintf(
			"cross-shape evidence schema %d is historical; record a schema %d run",
			evidence.SchemaVersion, CrossShapeSchemaVersion,
		)
		return criterion
	}

	var stale []string
	if evidence.SourceTreeSHA256 != current.SourceTreeSHA256 {
		stale = append(stale, "source tree")
	}
	if evidence.WeightsSHA256 != current.WeightsSHA256 {
		stale = append(stale, "retrieval weights")
	}
	for _, shape := range evidence.Shapes {
		if currentHash, ok := current.FixtureSets[shape.Kind]; !ok {
			stale = append(stale, shape.Kind+" fixture set unavailable")
		} else if shape.FixtureSetSHA256 != currentHash {
			stale = append(stale, shape.Kind+" fixtures")
		}
		if currentCount, ok := current.FixtureCounts[shape.Kind]; !ok {
			stale = append(stale, shape.Kind+" fixture count unavailable")
		} else if shape.G3.Fixtures != currentCount {
			stale = append(stale, fmt.Sprintf(
				"%s fixture coverage (%d measured, %d canonical)",
				shape.Kind, shape.G3.Fixtures, currentCount,
			))
		}
		if pinned, ok := current.PinnedCommits[shape.Kind]; ok &&
			!strings.EqualFold(shape.CommitSHA, pinned) {
			stale = append(stale, shape.Kind+" pinned commit")
		}
	}
	if len(stale) == 0 {
		return criterion
	}

	criterion.Verdict = Fail
	criterion.Detail = "cross-shape evidence is stale for current checkout: " + strings.Join(stale, ", ")
	return criterion
}

// CurrentCrossShapeIdentity hashes the build inputs, tuned retrieval weights,
// and the three canonical fixture directories using the same deterministic
// contracts used by the evidence producer.
func CurrentCrossShapeIdentity(repoRoot string) (CrossShapeCurrentIdentity, error) {
	repoRoot, err := filepath.Abs(repoRoot)
	if err != nil {
		return CrossShapeCurrentIdentity{}, fmt.Errorf("resolve repo root: %w", err)
	}
	sourceHash, err := crossShapeSourceTreeSHA256(repoRoot)
	if err != nil {
		return CrossShapeCurrentIdentity{}, err
	}
	weightsHash, err := crossShapeFileSHA256(filepath.Join(repoRoot, ".neurofs", "weights.json"))
	if err != nil {
		return CrossShapeCurrentIdentity{}, fmt.Errorf("hash retrieval weights: %w", err)
	}
	targetSourceHash, err := crossShapeTargetSourceTreeSHA256(repoRoot)
	if err != nil {
		return CrossShapeCurrentIdentity{}, fmt.Errorf("hash current Go target source tree: %w", err)
	}

	fixtureDirs := map[string]string{
		CrossShapeKindGoService:          filepath.Join(repoRoot, "audit", "facts"),
		CrossShapeKindPythonLibrary:      filepath.Join(repoRoot, "docs", "g5_fixtures", "click"),
		CrossShapeKindTypeScriptFrontend: filepath.Join(repoRoot, "docs", "g5_fixtures", "vue"),
	}
	fixtureSets := make(map[string]string, len(fixtureDirs))
	fixtureCounts := make(map[string]int, len(fixtureDirs))
	fixturesByKind := make(map[string][]Fixture, len(fixtureDirs))
	for kind, dir := range fixtureDirs {
		hash, err := crossShapeFixtureSetSHA256(dir)
		if err != nil {
			return CrossShapeCurrentIdentity{}, fmt.Errorf("hash %s fixtures: %w", kind, err)
		}
		fixtureSets[kind] = hash
		fixtures, err := LoadFixtures(dir)
		if err != nil {
			return CrossShapeCurrentIdentity{}, fmt.Errorf("load %s fixtures: %w", kind, err)
		}
		fixtureCounts[kind] = len(fixtures)
		fixturesByKind[kind] = fixtures
	}

	pinnedCommits := make(map[string]string, 2)
	for kind, dir := range map[string]string{
		CrossShapeKindPythonLibrary:      fixtureDirs[CrossShapeKindPythonLibrary],
		CrossShapeKindTypeScriptFrontend: fixtureDirs[CrossShapeKindTypeScriptFrontend],
	} {
		pin, err := crossShapePinnedCommit(filepath.Join(dir, "README.md"))
		if err != nil {
			return CrossShapeCurrentIdentity{}, fmt.Errorf("read %s pinned commit: %w", kind, err)
		}
		pinnedCommits[kind] = pin
	}
	return CrossShapeCurrentIdentity{
		SourceTreeSHA256: sourceHash,
		WeightsSHA256:    weightsHash,
		TargetSourceTrees: map[string]string{
			CrossShapeKindGoService: targetSourceHash,
		},
		FixtureSets:   fixtureSets,
		FixtureCounts: fixtureCounts,
		PinnedCommits: pinnedCommits,
		Fixtures:      fixturesByKind,
	}, nil
}

// BuildCrossShapeReportMetadata captures the effective runtime identity for a
// raw G5 command report. Callers opt into it explicitly with --g5-attest so
// ordinary economy/gate commands do not require a Git remote or persisted
// weights.
func BuildCrossShapeReportMetadata(
	repoRoot string,
	fixturesDir string,
	engineRoot string,
	hybridMode bool,
) (*CrossShapeReportMetadata, error) {
	repoRoot, err := filepath.Abs(repoRoot)
	if err != nil {
		return nil, fmt.Errorf("resolve measured repo root: %w", err)
	}
	if strings.TrimSpace(engineRoot) == "" {
		return nil, fmt.Errorf("engine source root is required")
	}
	engineRoot, err = filepath.Abs(engineRoot)
	if err != nil {
		return nil, fmt.Errorf("resolve engine source root: %w", err)
	}
	engineSourceHash, err := crossShapeSourceTreeSHA256(engineRoot)
	if err != nil {
		return nil, fmt.Errorf("hash engine source tree: %w", err)
	}
	stampedSourceHash := strings.TrimSpace(BuildSourceTreeSHA256)
	if stampedSourceHash == "" {
		return nil, fmt.Errorf(
			"measured executable has no engine source-tree provenance; build it with `make build`",
		)
	}
	if err := validateSHA256("embedded engine source-tree hash", stampedSourceHash); err != nil {
		return nil, err
	}
	if stampedSourceHash != engineSourceHash {
		return nil, fmt.Errorf(
			"measured executable was built from engine source tree %s, but --g5-engine-root hashes to %s; rebuild the binary",
			stampedSourceHash,
			engineSourceHash,
		)
	}
	targetSourceHash, err := crossShapeTargetSourceTreeSHA256(repoRoot)
	if err != nil {
		return nil, fmt.Errorf("hash measured target source tree: %w", err)
	}
	executable, err := os.Executable()
	if err != nil {
		return nil, fmt.Errorf("resolve measured executable: %w", err)
	}
	executable, err = filepath.EvalSymlinks(executable)
	if err != nil {
		return nil, fmt.Errorf("resolve measured executable symlinks: %w", err)
	}
	binaryHash, err := crossShapeFileSHA256(executable)
	if err != nil {
		return nil, fmt.Errorf("hash measured executable: %w", err)
	}
	weightsHash, err := crossShapeFileSHA256(filepath.Join(repoRoot, ".neurofs", "weights.json"))
	if err != nil {
		return nil, fmt.Errorf("hash measured retrieval weights: %w", err)
	}
	fixtureHash, err := crossShapeFixtureSetSHA256(fixturesDir)
	if err != nil {
		return nil, fmt.Errorf("hash measured fixture set: %w", err)
	}
	embeddingClient := embeddings.NewClient(hybridMode)
	commit, err := crossShapeGitOutput(repoRoot, "rev-parse", "HEAD")
	if err != nil {
		return nil, fmt.Errorf("resolve measured checkout commit: %w", err)
	}
	commit = strings.ToLower(strings.TrimSpace(commit))
	if len(commit) != 40 || !crossShapePinnedCommitPattern.MatchString(commit) {
		return nil, fmt.Errorf("measured checkout commit is not a full SHA-1: %q", commit)
	}
	remote, err := crossShapeGitOutput(repoRoot, "config", "--get", "remote.origin.url")
	if err != nil {
		return nil, fmt.Errorf("resolve measured checkout origin: %w", err)
	}
	remote = strings.TrimSpace(remote)
	if remote == "" {
		return nil, fmt.Errorf("measured checkout origin is empty")
	}
	status, err := crossShapeGitOutput(
		repoRoot,
		"status",
		"--porcelain=v1",
		"--untracked-files=all",
		"--ignored=matching",
		"--",
		".",
		":(exclude).neurofs",
		":(exclude).neurofs/**",
	)
	if err != nil {
		return nil, fmt.Errorf("inspect measured checkout dirtiness: %w", err)
	}
	return &CrossShapeReportMetadata{
		BinarySHA256:           binaryHash,
		EngineSourceTreeSHA256: engineSourceHash,
		TargetSourceTreeSHA256: targetSourceHash,
		WeightsSHA256:          weightsHash,
		FixtureSetSHA256:       fixtureHash,
		EmbeddingProvider:      embeddingClient.ProviderName(),
		EmbeddingModel:         embeddingClient.ModelName(),
		MockSemantic:           os.Getenv("NEUROFS_MOCK_SEMANTIC") == "1",
		RepoCommitSHA:          commit,
		RepoRemoteURL:          remote,
		RepoDirty:              strings.TrimSpace(status) != "",
	}, nil
}

// ComputeCrossShapeSourceTreeSHA256 exposes the exact build-input digest used
// by G5 to the hidden build helper. Normal callers should consume the stamped
// value through report metadata instead of reimplementing the contract.
func ComputeCrossShapeSourceTreeSHA256(repoRoot string) (string, error) {
	repoRoot, err := filepath.Abs(repoRoot)
	if err != nil {
		return "", fmt.Errorf("resolve engine source root: %w", err)
	}
	return crossShapeSourceTreeSHA256(repoRoot)
}

func crossShapeGitOutput(repoRoot string, args ...string) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "git", args...)
	cmd.Dir = repoRoot
	output, err := cmd.CombinedOutput()
	if err != nil {
		if ctx.Err() != nil {
			return "", ctx.Err()
		}
		return "", fmt.Errorf("%w: %s", err, strings.TrimSpace(string(output)))
	}
	return string(output), nil
}

// crossShapeTargetSourceTreeSHA256 binds a report to the exact fresh target
// corpus consumed by retrieval. The digest covers every indexed relative path
// and its persisted content checksum; RequiresSourceReindex first proves that
// this database generation still represents the complete indexable tree.
func crossShapeTargetSourceTreeSHA256(repoRoot string) (hash string, retErr error) {
	cfg, err := config.New(repoRoot)
	if err != nil {
		return "", err
	}
	if err := cfg.Validate(); err != nil {
		return "", err
	}
	db, err := storage.OpenReadOnly(cfg.DBPath)
	if err != nil {
		return "", fmt.Errorf("open target index read-only: %w", err)
	}
	defer func() {
		if err := db.Close(); err != nil {
			retErr = errors.Join(retErr, fmt.Errorf("close target index: %w", err))
		}
	}()

	stale, err := indexer.RequiresSourceReindex(cfg, db)
	if err != nil {
		return "", fmt.Errorf("verify target index freshness: %w", err)
	}
	if stale {
		return "", fmt.Errorf("target index is stale; run `neurofs scan` first")
	}
	files, err := db.AllFiles()
	if err != nil {
		return "", fmt.Errorf("load target index files: %w", err)
	}
	if len(files) == 0 {
		return "", fmt.Errorf("target index is empty; run `neurofs scan` first")
	}
	sort.Slice(files, func(i, j int) bool {
		return filepath.ToSlash(files[i].RelPath) < filepath.ToSlash(files[j].RelPath)
	})

	h := sha256.New()
	seen := make(map[string]bool, len(files))
	for i, file := range files {
		rel := filepath.ToSlash(filepath.Clean(file.RelPath))
		if rel == "." || filepath.IsAbs(file.RelPath) || rel == ".." ||
			strings.HasPrefix(rel, "../") {
			return "", fmt.Errorf("target index file %d has unsafe relative path %q", i, file.RelPath)
		}
		if seen[rel] {
			return "", fmt.Errorf("target index contains duplicate path %q", rel)
		}
		seen[rel] = true
		if err := validateSHA256("target index checksum for "+rel, file.Checksum); err != nil {
			return "", err
		}
		checksum, err := hex.DecodeString(file.Checksum)
		if err != nil {
			return "", fmt.Errorf("decode target index checksum for %s: %w", rel, err)
		}
		_, _ = h.Write([]byte(rel))
		_, _ = h.Write([]byte{0})
		_, _ = h.Write(checksum)
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// crossShapeSourceTreeSHA256 hashes every tracked or visible untracked engine
// build input plus the optional per-repository configuration that can change
// ranking or packing. Paths are part of the digest. Missing tracked paths are
// skipped: this both represents the effective source tree and keeps a digest
// stable when a staged deletion is committed.
func crossShapeSourceTreeSHA256(repoRoot string) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	cmd := exec.CommandContext(
		ctx,
		"git", "ls-files", "-z", "--cached", "--others", "--exclude-standard",
		"--", "*.go", "go.mod", "go.sum", "go.work", "go.work.sum", ".neurofsignore",
	)
	cmd.Dir = repoRoot
	raw, err := cmd.Output()
	if err != nil {
		if ctx.Err() != nil {
			return "", fmt.Errorf("list source inputs: %w", ctx.Err())
		}
		return "", fmt.Errorf("list source inputs: %w", err)
	}

	pathSet := make(map[string]bool)
	for _, rawPath := range bytes.Split(raw, []byte{0}) {
		if len(rawPath) > 0 {
			pathSet[string(rawPath)] = true
		}
	}
	buildInputs, err := crossShapeEffectiveBuildInputs(repoRoot)
	if err != nil {
		return "", err
	}
	for _, rel := range buildInputs {
		pathSet[rel] = true
	}
	// These files are normally ignored because they hold local state, but when
	// present they materially affect the measured ranking/packing behavior.
	for _, rel := range []string{
		".neurofs/config.json",
		".neurofs/ranking_weights.json",
	} {
		if info, statErr := os.Lstat(filepath.Join(repoRoot, filepath.FromSlash(rel))); statErr == nil {
			if !info.Mode().IsRegular() {
				return "", fmt.Errorf("source input is not a regular file: %s", rel)
			}
			pathSet[rel] = true
		} else if !os.IsNotExist(statErr) {
			return "", fmt.Errorf("inspect source input %s: %w", rel, statErr)
		}
	}
	paths := make([]string, 0, len(pathSet))
	for rel := range pathSet {
		paths = append(paths, rel)
	}
	sort.Strings(paths)

	h := sha256.New()
	count := 0
	for _, rel := range paths {
		clean := filepath.Clean(filepath.FromSlash(rel))
		if filepath.IsAbs(clean) || clean == ".." ||
			strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
			return "", fmt.Errorf("source input escapes repository: %q", rel)
		}

		path := filepath.Join(repoRoot, clean)
		info, statErr := os.Lstat(path)
		switch {
		case os.IsNotExist(statErr):
			continue
		case statErr != nil:
			return "", fmt.Errorf("inspect source input %s: %w", rel, statErr)
		case info.Mode()&os.ModeSymlink != 0:
			return "", fmt.Errorf("source input must not be a symlink: %s", rel)
		case info.Mode().IsRegular():
			digest, err := crossShapeFileDigest(path)
			if err != nil {
				return "", fmt.Errorf("hash source input %s: %w", rel, err)
			}
			count++
			_, _ = h.Write([]byte(filepath.ToSlash(clean)))
			_, _ = h.Write([]byte{0})
			_, _ = h.Write(digest)
		default:
			return "", fmt.Errorf("source input is not a regular file: %s", rel)
		}
	}
	if count == 0 {
		return "", fmt.Errorf("no Go build inputs found in %s", repoRoot)
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// crossShapeEffectiveBuildInputs asks the Go tool which repository files are
// actually compiled into cmd/neurofs. This supplements Git's source listing
// with ignored-but-compiled Go files, cgo inputs, and //go:embed assets such as
// the web UI. A synthetic unit-test repository without cmd/neurofs simply has
// no additional executable inputs.
func crossShapeEffectiveBuildInputs(repoRoot string) ([]string, error) {
	target := filepath.Join(repoRoot, "cmd", "neurofs")
	info, err := os.Stat(target)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("inspect cmd/neurofs: %w", err)
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("cmd/neurofs is not a directory")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, "go", "list", "-mod=readonly", "-deps", "-json", "./cmd/neurofs")
	cmd.Dir = repoRoot
	output, err := cmd.Output()
	if err != nil {
		if ctx.Err() != nil {
			return nil, fmt.Errorf("list effective Go build inputs: %w", ctx.Err())
		}
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			return nil, fmt.Errorf(
				"list effective Go build inputs: %w: %s",
				err, strings.TrimSpace(string(exitErr.Stderr)),
			)
		}
		return nil, fmt.Errorf("list effective Go build inputs: %w", err)
	}

	type listedPackage struct {
		Dir          string
		GoFiles      []string
		CgoFiles     []string
		CFiles       []string
		CXXFiles     []string
		MFiles       []string
		HFiles       []string
		FFiles       []string
		SFiles       []string
		SwigFiles    []string
		SwigCXXFiles []string
		SysoFiles    []string
		EmbedFiles   []string
	}
	decoder := json.NewDecoder(bytes.NewReader(output))
	paths := make(map[string]bool)
	for {
		var pkg listedPackage
		if err := decoder.Decode(&pkg); err != nil {
			if err == io.EOF {
				break
			}
			return nil, fmt.Errorf("decode effective Go build inputs: %w", err)
		}
		if pkg.Dir == "" {
			continue
		}
		fileGroups := [][]string{
			pkg.GoFiles,
			pkg.CgoFiles,
			pkg.CFiles,
			pkg.CXXFiles,
			pkg.MFiles,
			pkg.HFiles,
			pkg.FFiles,
			pkg.SFiles,
			pkg.SwigFiles,
			pkg.SwigCXXFiles,
			pkg.SysoFiles,
			pkg.EmbedFiles,
		}
		for _, files := range fileGroups {
			for _, name := range files {
				abs := filepath.Join(pkg.Dir, filepath.FromSlash(name))
				rel, err := filepath.Rel(repoRoot, abs)
				if err != nil || rel == ".." ||
					strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
					continue
				}
				paths[filepath.ToSlash(rel)] = true
			}
		}
	}
	out := make([]string, 0, len(paths))
	for rel := range paths {
		out = append(out, rel)
	}
	sort.Strings(out)
	return out, nil
}

func crossShapePinnedCommit(path string) (string, error) {
	data, _, err := fsutil.ReadRegularFileBounded(path, maxCrossShapeEvidenceBytes)
	if err != nil {
		return "", err
	}
	matches := crossShapePinnedCommitPattern.FindAllString(string(data), -1)
	unique := make(map[string]bool, len(matches))
	for _, match := range matches {
		unique[strings.ToLower(match)] = true
	}
	if len(unique) != 1 {
		return "", fmt.Errorf("want exactly one 40-character commit pin, found %d", len(unique))
	}
	for pin := range unique {
		return pin, nil
	}
	panic("unreachable")
}

// crossShapeFixtureSetSHA256 hashes sorted JSON basenames plus each file's
// binary SHA-256 digest. Using basenames makes a pinned fixture set portable
// across clone locations while still detecting renames and content changes.
func crossShapeFixtureSetSHA256(dir string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", err
	}
	var names []string
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}
		names = append(names, entry.Name())
	}
	sort.Strings(names)
	if len(names) == 0 {
		return "", fmt.Errorf("no JSON fixtures in %s", dir)
	}

	h := sha256.New()
	for _, name := range names {
		path := filepath.Join(dir, name)
		digest, err := crossShapeFileDigest(path)
		if err != nil {
			return "", fmt.Errorf("hash fixture %s: %w", name, err)
		}
		_, _ = h.Write([]byte(name))
		_, _ = h.Write([]byte{0})
		_, _ = h.Write(digest)
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

func crossShapeFileSHA256(path string) (string, error) {
	digest, err := crossShapeFileDigest(path)
	if err != nil {
		return "", err
	}
	return hex.EncodeToString(digest), nil
}

func crossShapeFileDigest(path string) ([]byte, error) {
	info, err := os.Lstat(path)
	if err != nil {
		return nil, err
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
		return nil, fmt.Errorf("path must be a regular non-symlink file: %s", path)
	}
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()
	h := sha256.New()
	if _, err := io.Copy(h, file); err != nil {
		return nil, err
	}
	return h.Sum(nil), nil
}

func validateCrossShapeEvidence(evidence *CrossShapeEvidence) (time.Time, error) {
	if evidence == nil {
		return time.Time{}, fmt.Errorf("evidence is nil")
	}
	if evidence.SchemaVersion != legacyCrossShapeSchemaVersion &&
		evidence.SchemaVersion != CrossShapeSchemaVersion {
		return time.Time{}, fmt.Errorf(
			"schema_version is %d, want %d or historical %d",
			evidence.SchemaVersion, CrossShapeSchemaVersion, legacyCrossShapeSchemaVersion,
		)
	}
	measuredAt, err := time.Parse(time.RFC3339, evidence.MeasuredAt)
	if err != nil {
		return time.Time{}, fmt.Errorf("measured_at must be RFC3339: %w", err)
	}
	if measuredAt.After(time.Now().Add(crossShapeMaxFutureSkew)) {
		return time.Time{}, fmt.Errorf(
			"measured_at is more than %s in the future",
			crossShapeMaxFutureSkew,
		)
	}
	switch evidence.ActorKind {
	case "agent", "human":
	default:
		return time.Time{}, fmt.Errorf("actor_kind must be agent or human")
	}
	if evidence.SignalKind != CrossShapeSignalKind {
		return time.Time{}, fmt.Errorf("signal_kind must be %q", CrossShapeSignalKind)
	}
	hashes := []struct {
		field string
		value string
	}{
		{field: "binary_sha256", value: evidence.BinarySHA256},
		{field: "weights_sha256", value: evidence.WeightsSHA256},
		{field: "source_tree_sha256", value: evidence.SourceTreeSHA256},
	}
	for _, hash := range hashes {
		if err := validateSHA256(hash.field, hash.value); err != nil {
			return time.Time{}, err
		}
	}
	if evidence.SchemaVersion == CrossShapeSchemaVersion {
		if evidence.RunConfig == nil {
			return time.Time{}, fmt.Errorf("run_config is required for schema %d", CrossShapeSchemaVersion)
		}
		if evidence.RunConfig.EmbeddingProvider != "mock" {
			return time.Time{}, fmt.Errorf("run_config.embedding_provider must be %q", "mock")
		}
		if evidence.RunConfig.EmbeddingModel != crossShapeEmbeddingModel {
			return time.Time{}, fmt.Errorf(
				"run_config.embedding_model must be %q",
				crossShapeEmbeddingModel,
			)
		}
		if evidence.RunConfig.EconomySearchLimit != crossShapeEconomySearchLimit {
			return time.Time{}, fmt.Errorf(
				"run_config.economy_search_limit must be %d",
				crossShapeEconomySearchLimit,
			)
		}
		if evidence.RunConfig.FixtureBudget != crossShapeFixtureBudget {
			return time.Time{}, fmt.Errorf(
				"run_config.fixture_budget must be %d",
				crossShapeFixtureBudget,
			)
		}
		if evidence.RunConfig.NoChunks {
			return time.Time{}, fmt.Errorf("run_config.no_chunks must be false")
		}
		if evidence.RunConfig.MockSemantic {
			return time.Time{}, fmt.Errorf("run_config.mock_semantic must be false")
		}
	}
	if len(evidence.Shapes) == 0 {
		return time.Time{}, fmt.Errorf("shapes must contain at least one repository shape")
	}

	names := make(map[string]bool, len(evidence.Shapes))
	kinds := make(map[string]bool, len(evidence.Shapes))
	for i := range evidence.Shapes {
		shape := &evidence.Shapes[i]
		location := fmt.Sprintf("shapes[%d]", i)
		if shape.Name == "" || shape.Name != strings.TrimSpace(shape.Name) {
			return time.Time{}, fmt.Errorf("%s.name must be non-empty without surrounding whitespace", location)
		}
		normalName := strings.ToLower(shape.Name)
		if names[normalName] {
			return time.Time{}, fmt.Errorf("duplicate shape name %q", shape.Name)
		}
		names[normalName] = true

		if !isRequiredCrossShapeKind(shape.Kind) {
			return time.Time{}, fmt.Errorf("%s.kind %q is not supported", location, shape.Kind)
		}
		if kinds[shape.Kind] {
			return time.Time{}, fmt.Errorf("duplicate shape kind %q", shape.Kind)
		}
		kinds[shape.Kind] = true

		if strings.TrimSpace(shape.RepoURL) == "" {
			return time.Time{}, fmt.Errorf("%s.repo_url is required", location)
		}
		if len(shape.CommitSHA) != 40 ||
			shape.CommitSHA != strings.ToLower(shape.CommitSHA) ||
			!crossShapePinnedCommitPattern.MatchString(shape.CommitSHA) {
			return time.Time{}, fmt.Errorf(
				"%s.commit_sha must be a full lowercase 40-character SHA-1",
				location,
			)
		}
		if err := validateSHA256(location+".fixture_set_sha256", shape.FixtureSetSHA256); err != nil {
			return time.Time{}, err
		}
		if err := validateVerdict(location+".economy.verdict", shape.Economy.Verdict); err != nil {
			return time.Time{}, err
		}
		if !isFinite(shape.Economy.MeanTokenReduction) || shape.Economy.MeanTokenReduction > 1 {
			return time.Time{}, fmt.Errorf("%s.economy.mean_token_reduction must be finite and <= 1", location)
		}
		if err := validateRatio(location+".economy.overall_recall", shape.Economy.OverallRecall); err != nil {
			return time.Time{}, err
		}
		if err := validateRatio(location+".economy.miss_rate", shape.Economy.MissRate); err != nil {
			return time.Time{}, err
		}
		if err := validateSHA256(location+".economy.report_sha256", shape.Economy.ReportSHA256); err != nil {
			return time.Time{}, err
		}
		if err := validateVerdict(location+".g2.verdict", shape.G2.Verdict); err != nil {
			return time.Time{}, err
		}
		if shape.G2.Bundles < 0 {
			return time.Time{}, fmt.Errorf("%s.g2.bundles must be non-negative", location)
		}
		if shape.G2.Overshoots < 0 || shape.G2.Overshoots > shape.G2.Bundles {
			return time.Time{}, fmt.Errorf("%s.g2.overshoots must be between 0 and bundles", location)
		}
		if evidence.SchemaVersion == CrossShapeSchemaVersion {
			if err := validateSHA256(location+".g2.report_sha256", shape.G2.ReportSHA256); err != nil {
				return time.Time{}, err
			}
		}
		if err := validateVerdict(location+".g3.verdict", shape.G3.Verdict); err != nil {
			return time.Time{}, err
		}
		if err := validateRatio(location+".g3.mean_recall", shape.G3.MeanRecall); err != nil {
			return time.Time{}, err
		}
		if shape.G3.Fixtures < 0 {
			return time.Time{}, fmt.Errorf("%s.g3.fixtures must be non-negative", location)
		}
		if shape.G3.Perfect < 0 || shape.G3.Perfect > shape.G3.Fixtures {
			return time.Time{}, fmt.Errorf("%s.g3.perfect must be between 0 and fixtures", location)
		}
		if evidence.SchemaVersion == CrossShapeSchemaVersion {
			if err := validateSHA256(location+".g3.report_sha256", shape.G3.ReportSHA256); err != nil {
				return time.Time{}, err
			}
		}
		if shape.Bench != nil {
			if shape.Bench.Questions <= 0 {
				return time.Time{}, fmt.Errorf("%s.bench.questions must be positive", location)
			}
			if !isFinite(shape.Bench.Top3Percent) ||
				shape.Bench.Top3Percent < 0 ||
				shape.Bench.Top3Percent > 100 {
				return time.Time{}, fmt.Errorf("%s.bench.top3_percent must be between 0 and 100", location)
			}
			if err := validateSHA256(location+".bench.report_sha256", shape.Bench.ReportSHA256); err != nil {
				return time.Time{}, err
			}
		}
	}
	return measuredAt, nil
}

func requiredCrossShapeKinds() []string {
	return []string{
		CrossShapeKindGoService,
		CrossShapeKindPythonLibrary,
		CrossShapeKindTypeScriptFrontend,
	}
}

func isRequiredCrossShapeKind(kind string) bool {
	for _, required := range requiredCrossShapeKinds() {
		if kind == required {
			return true
		}
	}
	return false
}

func validateSHA256(field, value string) error {
	if len(value) != 64 {
		return fmt.Errorf("%s must be 64 hexadecimal characters", field)
	}
	if value != strings.ToLower(value) {
		return fmt.Errorf("%s must use lowercase hexadecimal", field)
	}
	if _, err := hex.DecodeString(value); err != nil {
		return fmt.Errorf("%s must be 64 hexadecimal characters", field)
	}
	return nil
}

func validateVerdict(field string, verdict Verdict) error {
	switch verdict {
	case Pass, Warn, Fail, Skip:
		return nil
	default:
		return fmt.Errorf("%s has unknown verdict %q", field, verdict)
	}
}

func validateRatio(field string, value float64) error {
	if !isFinite(value) || value < 0 || value > 1 {
		return fmt.Errorf("%s must be between 0 and 1", field)
	}
	return nil
}

func isFinite(value float64) bool {
	return !math.IsNaN(value) && !math.IsInf(value, 0)
}
